defaults:
  - default
  - _self_

# Override from `default` config
id: pkm_battle_env_wrapper
capture_video: False
#num_envs: 4
#bunch of other ones that can be repeated

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.pkm_battle_env_wrapper.PkmBattleEnvWrapper
  id: ${env.id}
  #seed: ${seed}